import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import {unstable_setRequestLocale} from 'next-intl/server';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const locales = ['en', 'hr'];

export default function RootLayout({ children, params: {locale} }: { children: React.ReactNode, params: any }) {
  
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();
 
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
